# Generated by Django 2.1.2 on 2019-09-20 21:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('soft_deleted', models.BooleanField(blank=True, db_index=True, default=False, editable=False)),
                ('enabled', models.BooleanField(blank=True, db_index=True, default=True, editable=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='user name')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Gender')),
                ('birth_date', models.DateField(null=True, verbose_name='Birth Date')),
                ('birth_place', models.CharField(max_length=100, null=True, verbose_name='Birth Place')),
                ('last_certificate', models.CharField(max_length=300, null=True, verbose_name='last certificate')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='cell phone')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
