from django.conf import settings


TOKEN_CREATOR = getattr(settings, 'SECURITY_TOKEN_CREATOR')
SERIALIZERS = getattr(settings, 'SECURITY_AUTH_SERIALIZERS', {})

TOKEN_SERIALIZER = SERIALIZERS.get('SECURITY_TOKEN_SERIALIZER')
LOGIN_SERIALIZER = SERIALIZERS.get('SECURITY_LOGIN_SERIALIZER')
